<?php
if($_SERVER['SERVER_NAME'] == "localhost") {
  echo "<div style='width:100%;height:90px;'></div>";
} else {
  echo '
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>

<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-8221672957358875"
     data-ad-slot="1042173452"
     data-ad-format="auto"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
  ';
}
?>
