<footer>
<div class="container-fluid" id="rodape">
  <div class="coluna-rodape">
    <h4>Dados do usuário:</h4>
    <?=$email.":".$privilegio.":".$credencial?>
    <h4>Ambiente Online:</h4>
    <?=$ambiente.":".$grupo?>
  </div>
  <div class="coluna-rodape">

  </div>
  <div class="coluna-rodape">

  </div>
</div>
<div class="container-fluid" style="border-top:1px solid #ddd;padding:20px;">
  <div class="container">
    <span style="float:left;width:49%;">
      <p>Site desenvolvido pela equipe Costeau desenvolvimento.</p>
    </span>
    <span style="float:right;width:49%;text-align:right;">
      <i class="fa fa-cloud"></i> Ambiente Online
    </span>
  </div>
</div>
</footer>
